# Generated by Django 2.2.6 on 2019-10-31 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='church',
            table=None,
        ),
    ]
