# Generated by Django 2.2.6 on 2019-10-31 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0004_auto_20191031_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='lat',
            field=models.DecimalField(decimal_places=10, default='0', max_digits=19),
        ),
        migrations.AddField(
            model_name='church',
            name='lng',
            field=models.DecimalField(decimal_places=10, default='0', max_digits=19),
        ),
    ]
