# Generated by Django 2.2.6 on 2019-10-31 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0005_auto_20191031_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='lat',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
        migrations.AlterField(
            model_name='church',
            name='lng',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
    ]
