# Generated by Django 2.2.6 on 2019-11-05 19:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('churches', '0008_auto_20191031_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=800)),
                ('address', models.CharField(max_length=350)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='church',
            name='subscribers',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='church',
            name='events',
            field=models.ManyToManyField(related_name='events', to='churches.Event'),
        ),
    ]
