# Generated by Django 2.2.6 on 2019-11-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_subscriber'),
        ('churches', '0010_remove_church_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscribers', to='accounts.Subscriber'),
        ),
    ]
