# Generated by Django 2.2.6 on 2019-11-06 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0011_church_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='church',
            name='events',
        ),
        migrations.AddField(
            model_name='event',
            name='church',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='churches.Church'),
        ),
        migrations.AlterField(
            model_name='church',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to='accounts.Subscriber'),
        ),
    ]
