# Generated by Django 2.2.6 on 2019-10-28 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=800)),
                ('is_verified', models.BooleanField(default=False)),
                ('denoimonation', models.CharField(choices=[('NON DENIMONATIONAL', 'Non Denominational'), ('CATHOLIC', 'Catholic'), ('ADVENTIST', 'Adventist'), ('ANABAPTIST', 'Anabaptist'), ('ANGLICAN', 'Anglican'), ('BAPTIST', 'Baptist'), ('CALVINIST', 'Calvinist'), ('EVANGELICAL', 'Evangelical'), ('HOLINESS', 'Holiness'), ('LUTHERAN', 'Lutheran'), ('METHODIST', 'Methodist'), ('PENTECOSTAL', 'Pentecostal'), ('ASSYRIAN', 'Assyrian'), ('EASTERN ORTHODOX', 'Eastern Orthodox'), ('ORIENTAL ORTHODOX', 'Oriental Orthodox'), ("JEHOVAH'S WITNESS", "Jehovah's Witness"), ('LATTER DAY SAINT', 'Latter Day Saint')], max_length=255)),
                ('website', models.URLField(max_length=255)),
                ('worship_type', models.CharField(choices=[('LITURGICAL', 'Liturgical'), ('TRADITIONAL', 'Traditional'), ('BLENDED', 'Blended'), ('CONTEMPORARY', 'Contemporary'), ('MODERN', 'Modern')], max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
