# Generated by Django 2.2.6 on 2019-10-31 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191031_1444'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
