# Generated by Django 2.2.6 on 2019-11-07 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0013_auto_20191107_2124'),
        ('accounts', '0006_subscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
